pipeline {
    agent any
    environment {
//        pastaWS = "$WORKSPACE/prova_ec2-jenkins-Rafael_Carvalho_E_Lima/ProvaN22_appfast"
        pastaWS = "$WORKSPACE/ProvaN22_appfast"
    }
    stages {
        stage('Preparando area de trabalho') {
            steps {
                echo 'preparando Wrapper'
                echo "$pastaWS"
                dir("pastaWS") {

                    sh './gradlew'
                }
            }
        }
        stage('teste unitario') {
            steps {
                echo 'Testando'
                dir("$pastaWS") {
                    sh './gradlew test'
                }
            }
        }
        stage('Building') {
            steps {
                echo 'montando aplicativo'
                dir("$pastaWS") {
                    sh './gradlew assembleRelease'
                }
            }
        }
        stage('Arquivando') {
            steps {
                echo 'Arquivando o aplicativo'
                archiveArtifacts artifacts: '**/app-release-unsigned.apk', fingerprint: true, allowEmptyArchive: true
            }
        }
    }
}